'use client';
import {CategoryPie,BudgetBars,CashCandles,NextMonthScenario} from '@/components/dashboard-charts';
import {readApiResponse} from '@/lib/api-response';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Wallet,LayoutDashboard,ReceiptText,Target,PiggyBank,Settings2,BookOpen,ChevronLeft,ChevronRight,ArrowUpRight,ArrowDownRight,ArrowRight,LogOut,Download,Check,Plus,Save,LoaderCircle,RefreshCw,Menu,X,ShieldCheck,BriefcaseBusiness,TrendingUp,AlertCircle,CheckCircle2,PawPrint,Utensils,ShoppingBag,House,Heart,GraduationCap,Gamepad2,Receipt,ShoppingCart,CircleHelp,CreditCard,Wrench,HeartPulse,Monitor,ArrowLeftRight,Car,Plane,Sun,Moon,type LucideIcon} from 'lucide-react';
import {CATEGORIES,DEFAULT_SETTINGS,KIND_NAMES,blankMonth,brl,emptyAmounts,hasValues,inputAmount,missing,monthLabel,parseAmount,reserveSnapshot,shiftMonth,summary,total,type Amounts,type CategoryId,type Kind,type Month,type Settings,type Store} from '@/lib/finance';
type View='actual'|'plan'|'dashboard'|'reserves'|'settings'|'guide';
const NAV:{id:View;label:string;icon:LucideIcon}[]=[{id:'actual',label:'Gastos do mês',icon:ReceiptText},{id:'plan',label:'Planejamento',icon:Target},{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'reserves',label:'Reservas',icon:PiggyBank},{id:'settings',label:'Configurações',icon:Settings2},{id:'guide',label:'Como usar',icon:BookOpen}];
const ICONS:Record<string,LucideIcon>={paw:PawPrint,utensils:Utensils,bag:ShoppingBag,home:House,heart:Heart,book:GraduationCap,game:Gamepad2,receipt:Receipt,piggy:PiggyBank,cart:ShoppingCart,circle:CircleHelp,card:CreditCard,tool:Wrench,wallet:Wallet,cross:HeartPulse,monitor:Monitor,transfer:ArrowLeftRight,car:Car,plane:Plane};
function ThemeToggle(){const [dark,setDark]=useState(false);
 useEffect(()=>setDark(document.documentElement.dataset.theme==='dark'),[]);
 function toggle(){const next=dark?'light':'dark';document.documentElement.dataset.theme=next;localStorage.tema=next;setDark(!dark);}
 return <button className="icon-button" onClick={toggle} aria-label={dark?'Usar tema claro':'Usar tema escuro'} title={dark?'Tema claro':'Tema escuro'}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button>;}
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{const res=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(res.status===401){window.location.reload();throw Error('Sua sessão expirou.');}return readApiResponse<T>(res);}
const calendarNow=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).format(new Date());
function Status({month,settings}:{month:Month;settings:Settings}){const has=hasValues(month.actual,settings),complete=missing(month,settings).length===0;return <span className={`badge ${month.status==='closed'&&complete?'success':''}`}>{month.status==='closed'&&complete?<CheckCircle2 size={14}/>:null}{!has?'Sem lançamentos':month.status==='closed'&&complete?'Mês fechado':month.status==='closed'?'Revisar valores':'Em andamento'}</span>;}
function Metric({label,value,icon:Icon,tone='',foot}:{label:string;value:string;icon:LucideIcon;tone?:string;foot?:string}){return <article className={'metric '+tone}><div className="metric-top"><span>{label}</span><Icon size={19}/></div><strong>{value}</strong>{foot&&<small>{foot}</small>}</article>;}
function Empty({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="empty"><span className="empty-icon"><ReceiptText size={27}/></span><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>;}
export default function FinanceApp(){
 const [store,setStore]=useState<Store|null>(null),[view,setView]=useState<View>('actual'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[menu,setMenu]=useState(false);
 const load=useCallback(async()=>{try{const data=await api<Store>('/api/data');setStore(data);setSelected(s=>s||[calendarNow(),data.settings.startMonth].sort().at(-1)!);setError('');setDirty(false);}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return ()=>clearTimeout(t);},[notice]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 function change(next:()=>void){if(dirty&&!window.confirm('Há alterações não salvas. Deseja sair sem salvar?'))return;setDirty(false);setMenu(false);next();}
 function saved(month:Month){setStore(s=>s?{...s,months:[...s.months.filter(m=>m.month!==month.month),month].sort((a,b)=>a.month.localeCompare(b.month))}:s);setDirty(false);setNotice(month.status==='closed'?'Mês salvo e fechado.':'Valores salvos.');}
 async function signOut(){change(()=>{void api('/api/auth/logout','POST').then(()=>window.location.reload()).catch(e=>setError(e.message));});}
 if(!store||!selected)return <main className="loading-screen"><Wallet size={38}/><h1>Meu Financeiro</h1>{error?<><p role="alert">{error}</p><button className="button primary" onClick={load}>Tentar novamente</button></>:<LoaderCircle className="spin"/>}</main>;
 const month=store.months.find(m=>m.month===selected)||blankMonth(selected,store.settings),reserve=reserveSnapshot(store,selected);
 const nav=(id:View)=>change(()=>setView(id));
 return <div className="app-shell"><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Fechar menu':'Abrir menu'}>{menu?<X/>:<Menu/>}</button>{menu&&<button className="sidebar-backdrop" aria-label="Fechar menu" onClick={()=>setMenu(false)}/>}
 <aside className={'sidebar '+(menu?'open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('actual');}}><span className="brand-icon"><Wallet size={23}/></span><span>meu<br/><b>financeiro</b></span></a><div className="nav-label">SEU DINHEIRO</div><nav>{NAV.map(({id,label,icon:Icon},i)=><button key={id} onClick={()=>nav(id)} className={`${view===id?'active':''} ${i===4?'nav-separator':''}`} aria-current={view===id?'page':undefined}><Icon size={20}/><span>{label}</span>{view===id&&<span className="nav-indicator"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-goal"><PiggyBank size={22}/><span>Um mês de cada vez<strong>{brl(store.settings.monthlyGoal)} <small>/ mês</small></strong></span></div><button onClick={signOut} className="logout"><LogOut size={17}/> Sair da conta</button></div></aside>
 <main className="workspace"><header className="topbar"><span className="breadcrumb">Pessoal <span>/</span> {NAV.find(n=>n.id===view)?.label}</span><span className="topbar-right"><ThemeToggle/><span className="private-label"><ShieldCheck size={15}/> Meu espaço</span></span></header><div className="content"><div className="page-heading"><div><span className="eyebrow">{view==='actual'?'ACOMPANHAMENTO MENSAL':view==='plan'?'PRÓXIMOS PASSOS':view==='reserves'?'SEUS OBJETIVOS':'VISÃO FINANCEIRA'}</span><h1>{NAV.find(n=>n.id===view)?.label}</h1></div>{!['settings','guide'].includes(view)&&<div className="month-picker"><button className="icon-button" aria-label="Mês anterior" disabled={selected<=store.settings.startMonth} onClick={()=>change(()=>setSelected(shiftMonth(selected,-1)))}><ChevronLeft size={19}/></button><input type="month" aria-label="Mês de referência" min={store.settings.startMonth} max="2099-12" value={selected} onChange={e=>{const v=e.target.value;if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(v)&&v>=store.settings.startMonth)change(()=>setSelected(v));}}/><button className="icon-button" aria-label="Próximo mês" disabled={selected>='2099-12'} onClick={()=>change(()=>setSelected(shiftMonth(selected,1)))}><ChevronRight size={19}/></button></div>}</div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>change(()=>void load())}>Recarregar</button></div>}
 {(view==='actual'||view==='plan')&&<MonthEditor key={`${view}-${selected}-${month.version}-${store.settingsVersion}`} month={month} settings={store.settings} mode={view} allMonths={store.months} onSave={saved} onDirty={setDirty} onReload={()=>change(()=>void load())}/>}
 {view==='dashboard'&&<Dashboard store={store} month={month} onEdit={()=>nav('actual')} onMonth={m=>change(()=>{setSelected(m);setView('actual');})} onPlan={()=>change(()=>{setSelected(shiftMonth(selected,1));setView('plan');})}/>}
 {view==='reserves'&&<Reserves store={store} month={selected} reserve={reserve} onSettings={()=>nav('settings')}/>}
 {view==='settings'&&<SettingsEditor key={store.settingsVersion} store={store} onDirty={setDirty} onSave={(settings,version)=>{setStore({...store,settings,settingsVersion:version});setDirty(false);setNotice('Configurações salvas.');}} onReload={()=>change(()=>void load())}/>}
 {view==='guide'&&<Guide/>}
 </div><footer className="app-footer"><span>Meu Financeiro</span><span>Seu planejamento, no seu ritmo.</span></footer></main>{notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}</div>;
}
function MonthEditor({month,settings,mode,allMonths,onSave,onDirty,onReload}:{month:Month;settings:Settings;mode:'actual'|'plan';allMonths:Month[];onSave:(m:Month)=>void;onDirty:(d:boolean)=>void;onReload:()=>void}){
 const planned=mode==='plan',initial=planned?month.planned:month.actual;
 const [fields,setFields]=useState<Record<CategoryId,string>>(()=>Object.fromEntries(CATEGORIES.map(c=>[c.id,inputAmount(initial[c.id])])) as Record<CategoryId,string>);
 const [other,setOther]=useState(inputAmount(month.otherInvestments)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[invalid,setInvalid]=useState<string[]>([]);
 const values=useMemo(()=>Object.fromEntries(CATEGORIES.map(c=>{try{return [c.id,parseAmount(fields[c.id])];}catch{return [c.id,null];}})) as Amounts,[fields]);
 const dirty=CATEGORIES.some(c=>fields[c.id]!==inputAmount(initial[c.id]))||(!planned&&other!==inputAmount(month.otherInvestments));
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 const preview={...month,[planned?'planned':'actual']:values,otherInvestments:(()=>{try{return parseAmount(other)??0;}catch{return 0;}})()};const stats=summary(preview,settings);
 const income=total(values,'income',settings),expenses=total(values,'expense',settings),investment=total(values,'saving',settings),present=hasValues(values,settings),hasIncome=hasValues(values,settings,'income');
 const filled=CATEGORIES.filter(c=>settings.kinds[c.id]!=='neutral'&&values[c.id]!==null).length,count=CATEGORIES.filter(c=>settings.kinds[c.id]!=='neutral').length;
 async function save(close=false){setError('');setInvalid([]);try{const parsed=emptyAmounts(),bad:string[]=[];for(const c of CATEGORIES){try{parsed[c.id]=parseAmount(fields[c.id]);if((parsed[c.id]??0)<0&&(planned||settings.kinds[c.id]!=='saving'))bad.push(c.id);}catch{bad.push(c.id);}}let otherValue=0;try{otherValue=parseAmount(other)??0;}catch{bad.push('other');}if(bad.length){setInvalid(bad);throw Error('Confira os campos destacados. Use valores como 1.250,50.');}
 const payload={...month,[planned?'planned':'actual']:parsed,otherInvestments:planned?month.otherInvestments:otherValue,status:planned?month.status:close?'closed':'draft'} as Month;
 if(close&&missing(payload,settings).length){setInvalid(missing(payload,settings).map(c=>c.id));throw Error('Faltam valores para fechar o mês. Preencha os campos vazios ou use “Sem movimento = zero”.');}
 setBusy(true);onSave(await api<Month>('/api/month','PUT',payload));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function copyPrevious(){const prev=allMonths.find(m=>m.month===shiftMonth(month.month,-1));if(!prev){setError('Não há planejamento salvo no mês anterior.');return;}if(dirty&&!window.confirm('Substituir os valores desta tela pelas metas do mês anterior?'))return;setFields(Object.fromEntries(CATEGORIES.map(c=>[c.id,inputAmount(prev.planned[c.id])])) as Record<CategoryId,string>);setError('');}
 const groups:{kind:Kind;label:string}[]=[{kind:'income',label:'RECEBIMENTOS'},{kind:'expense',label:'DESPESAS POR CATEGORIA'},{kind:'saving',label:'INVESTIMENTOS E CAIXINHAS'},{kind:'neutral',label:'MOVIMENTAÇÕES NEUTRAS'}];
 return <><div className="metrics three"><Metric icon={Wallet} label={planned?'Renda prevista':'Recebimentos'} value={hasIncome?brl(income):'—'}/><Metric icon={ReceiptText} label={planned?'Limites de despesas':'Gastos registrados'} value={present?brl(expenses):'—'}/><Metric icon={planned?Target:PiggyBank} tone="accent" label={planned?'Disponível após planejar':'Guardado para reservas'} value={planned?(hasIncome?brl(income-expenses-investment):'—'):(stats.hasSaving?brl(stats.reserved):'—')} foot={planned?`Meta de aporte: ${brl(settings.monthlyGoal)}`:`Meta do mês: ${brl(settings.monthlyGoal)}`}/></div>
 <section className="panel editor-panel"><div className="panel-heading"><div><h2>{planned?'Suas metas para o mês':'Quanto você gastou?'}</h2><div className="inline-meta"><span className="capitalize">{monthLabel(month.month)}</span>{!planned&&<Status month={month} settings={settings}/>}<span>{filled} de {count} categorias</span></div></div><div className="editor-tools">{planned?<button className="button subtle" onClick={copyPrevious} disabled={busy}><RefreshCw size={16}/> Copiar mês anterior</button>:<button className="button subtle" disabled={busy} onClick={()=>{setFields(p=>Object.fromEntries(CATEGORIES.map(c=>[c.id,p[c.id].trim()?p[c.id]:'0,00'])) as Record<CategoryId,string>);setInvalid([]);}}><Check size={16}/> Sem movimento = zero</button>}</div></div>
 <div className="category-table"><div className="category-table-header"><span>Categoria</span><span>{planned?'Meta mensal':'Valor do mês'}</span><span>{planned?'':'Meta / diferença'}</span></div>
 {groups.map(group=>{const categories=CATEGORIES.filter(c=>settings.kinds[c.id]===group.kind);if(!categories.length)return null;return <div className={'category-group '+group.kind} key={group.kind}><div className="group-title"><span>{group.label}</span><span>{hasValues(values,settings,group.kind)?brl(total(values,group.kind,settings)):'—'}</span></div>{categories.map(c=>{const Icon=ICONS[c.icon],budget=month.planned[c.id],spent=values[c.id],over=!planned&&group.kind==='expense'&&spent!==null&&budget!==null?spent-budget:null;return <div className={'category-row '+(invalid.includes(c.id)?'invalid-row':'')} key={c.id}><label htmlFor={mode+c.id} className="category-name"><span className={'category-icon '+group.kind}><Icon size={19}/></span><span>{c.name}</span></label><div className={'amount-field '+(invalid.includes(c.id)?'invalid':'')}><span>R$</span><input id={mode+c.id} inputMode="decimal" autoComplete="off" placeholder="0,00" aria-invalid={invalid.includes(c.id)} value={fields[c.id]} disabled={busy} onChange={e=>{setFields({...fields,[c.id]:e.target.value});setInvalid(p=>p.filter(x=>x!==c.id));}}/></div><div className="row-comparison">{!planned&&(group.kind==='expense'?<><span>{budget===null?'Sem meta':brl(budget)}</span>{over!==null&&(over>0?<small className="negative">+{brl(over)} acima</small>:<small className="positive">{brl(-over)} disponível</small>)}</>:<span className="type-label">{KIND_NAMES[group.kind]}</span>)}</div></div>;})}</div>;})}</div>
 {!planned&&<div className="other-investments"><label htmlFor="other-investments">Outros investimentos fora das reservas</label><div className={'amount-field '+(invalid.includes('other')?'invalid':'')}><span>R$</span><input id="other-investments" inputMode="decimal" value={other} disabled={busy} onChange={e=>setOther(e.target.value)}/></div></div>}
 {error&&<div className="editor-error error-banner" role="alert"><span><AlertCircle size={18}/>{error}</span><button onClick={onReload}>Recarregar dados</button></div>}
 <div className="save-bar"><div><span className={'save-state '+(dirty?'unsaved':'')}><span/>{dirty?'Alterações não salvas':month.version?'Tudo salvo':'Ainda não salvo'}</span>{!planned&&stats.hasIncome&&<strong>Saldo após aportes <span className={stats.balance<0?'negative':''}>{brl(stats.balance)}</span></strong>}</div><div className="save-actions">{!planned&&<button className="button secondary" onClick={()=>save(true)} disabled={busy}><CheckCircle2 size={17}/> Salvar e fechar mês</button>}<button className="button primary" onClick={()=>save(false)} disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>} {planned?'Salvar metas':'Salvar gastos'}</button></div></div></section></>;
}
function Dashboard({store,month,onEdit,onMonth,onPlan}:{store:Store;month:Month;onEdit:()=>void;onMonth:(m:string)=>void;onPlan:()=>void}){
 const s=summary(month,store.settings),pending=missing(month,store.settings).length,year=month.month.slice(0,4),yearMonths=store.months.filter(m=>m.month.startsWith(year)&&hasValues(m.actual,store.settings));
 return <>{pending>0&&<p className="dashboard-partial">{s.hasData?`Mês parcial: ${pending} categorias ainda sem valor. Os indicadores mostram apenas o que foi informado.`:'Este mês ainda não tem lançamentos. Registre os totais para começar a análise.'}</p>}<div className="metrics four"><Metric icon={Wallet} label="Entrou no mês" value={s.hasIncome?brl(s.income):'—'}/><Metric icon={ArrowDownRight} label="Saiu em despesas" value={hasValues(month.actual,store.settings,'expense')?brl(s.expenses):'—'} foot="Sem aportes e transferências"/><Metric icon={PiggyBank} label="Aportes líquidos" tone="accent" value={s.hasSaving?brl(s.invested):'—'} foot="Negativo significa resgate"/><Metric icon={ArrowUpRight} label="Sobra após aportes" tone={s.balance<0?'danger':''} value={s.hasIncome?brl(s.balance):'—'} foot={pending?'Parcial · faltam valores':'Entradas − despesas − aportes'}/></div>
 <section className="goal-strip"><div className="goal-icon"><Target size={23}/></div><div><span>Meta de guardar no mês</span><strong>{s.hasSaving?brl(s.reserved):'—'} <small>/ {brl(store.settings.monthlyGoal)}</small></strong></div><div className="goal-track"><div className="progress"><span style={{width:`${Math.max(0,Math.min(100,s.reserved/(store.settings.monthlyGoal||1)*100))}%`}}/></div><span>{s.hasSaving?s.remaining===0?'Meta alcançada':`Faltam ${brl(s.remaining)}`:'Aguardando os aportes do mês'}</span></div><button className="button secondary" onClick={onEdit}>Registrar gastos <ArrowRight size={17}/></button></section>
 <CashCandles key={month.month} store={store} month={month.month} onMonth={onMonth}/>
 <div className="dashboard-grid decision-charts"><CategoryPie key={month.month} month={month} settings={store.settings}/><BudgetBars month={month} settings={store.settings}/></div>
 {month.month<'2099-12'&&<NextMonthScenario key={`${month.month}-${store.settingsVersion}`} store={store} month={month.month} onPlan={onPlan}/>}
 <section className="panel history-panel"><div className="panel-heading"><h2>Histórico mensal</h2><span className="muted">{yearMonths.length} {yearMonths.length===1?'mês registrado':'meses registrados'}</span></div>{!yearMonths.length?<Empty title="Nenhum mês registrado neste ano" action={<button onClick={onEdit} className="button primary"><Plus size={17}/> Registrar primeiro mês</button>}/>:<div className="table-scroll"><table><thead><tr><th>Mês</th><th>Recebimentos</th><th>Despesas</th><th>Para reservas</th><th>Saldo</th><th>Situação</th><th><span className="sr-only">Abrir</span></th></tr></thead><tbody>{yearMonths.map(m=>{const t=summary(m,store.settings);return <tr key={m.month}><td className="capitalize">{monthLabel(m.month,true)}</td><td>{t.hasIncome?brl(t.income):'—'}</td><td>{brl(t.expenses)}</td><td>{t.hasSaving?brl(t.reserved):'—'}</td><td className={t.balance<0?'negative':''}>{t.hasIncome?brl(t.balance):'—'}</td><td><Status month={m} settings={store.settings}/></td><td><button className="icon-button" aria-label={`Abrir ${monthLabel(m.month)}`} onClick={()=>onMonth(m.month)}><ArrowUpRight size={18}/></button></td></tr>;})}</tbody></table></div>}</section></>;
}
function Reserves({store,month,reserve,onSettings}:{store:Store;month:string;reserve:ReturnType<typeof reserveSnapshot>;onSettings:()=>void}){
 const s=store.settings;return <><section className="reserve-hero"><div><span className="eyebrow">CONSTRUINDO TRANQUILIDADE</span><h2>Suas próximas conquistas.</h2><span className="muted">Acumulado estimado até <span className="capitalize">{monthLabel(month)}</span></span><strong className={reserve.accumulated<0?'negative':''}>{brl(reserve.accumulated)}</strong></div><div className="reserve-hero-meta"><span className="reserve-emblem"><PiggyBank size={36}/></span><span>Meta mensal<strong>{brl(s.monthlyGoal)}</strong></span></div></section>
 {reserve.accumulated<0&&<div className="error-banner" role="alert">Os resgates superam o saldo calculado. Confira os saldos iniciais e os aportes registrados.</div>}
 <div className="reserve-cards">{[{title:'Reserva de emergência',n:'01',icon:ShieldCheck,goal:s.emergencyGoal,current:reserve.emergency,time:reserve.monthsToEmergency,tag:'Primeira prioridade'},{title:'Caixa da empresa',n:'02',icon:BriefcaseBusiness,goal:s.businessGoal,current:reserve.business,time:reserve.monthsToBoth,tag:'Depois da emergência'}].map(({title,n,icon:Icon,goal,current,time,tag})=><section className="panel reserve-card" key={n}><div className="reserve-card-top"><span className="reserve-card-icon"><Icon size={25}/></span><span className="step-number">{n}</span></div><span className="eyebrow">{tag}</span><h2>{title}</h2><div className="reserve-value">{current===null?'—':brl(current)}<span>de {goal===null?'meta a definir':brl(goal)}</span></div><div className="progress"><span style={{width:`${goal===null||current===null?0:goal===0?100:Math.max(0,Math.min(100,current/goal*100))}%`}}/></div><div className="reserve-card-foot"><span>{goal===null?<button className="text-button" onClick={onSettings}>Definir meta <ArrowRight size={15}/></button>:current===null?'Defina a meta de emergência':current>=goal?'Meta alcançada':`${brl(goal-current)} para completar`}</span><span>{time===null?'':time===0?'Concluída':`~ ${time} ${time===1?'mês':'meses'}`}</span></div></section>)}</div>
 <div className="metrics three"><Metric label="Saldo inicial combinado" icon={Wallet} value={brl(s.emergencyOpening+s.businessOpening)}/><Metric label="Aportes líquidos acumulados" icon={TrendingUp} value={brl(reserve.contributions)}/><Metric label="Ritmo planejado" icon={Target} value={brl(s.monthlyGoal)} foot="por mês"/></div><div className="reserve-note"><BookOpen size={18}/><span>Destinação sugerida, sem rendimentos. As regras estão em “Como usar”.</span></div></>;
}
function SettingsEditor({store,onSave,onDirty,onReload}:{store:Store;onSave:(s:Settings,v:number)=>void;onDirty:(d:boolean)=>void;onReload:()=>void}){
 const initial=store.settings;const keys=['monthlyGoal','emergencyGoal','businessGoal','emergencyOpening','businessOpening'] as const;
 const [fields,setFields]=useState(()=>Object.fromEntries(keys.map(k=>[k,inputAmount(initial[k])])) as Record<typeof keys[number],string>),[start,setStart]=useState(initial.startMonth),[kinds,setKinds]=useState(initial.kinds),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=keys.some(k=>fields[k]!==inputAmount(initial[k]))||start!==initial.startMonth||JSON.stringify(kinds)!==JSON.stringify(initial.kinds);useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 async function save(){setError('');setBusy(true);try{const amounts=Object.fromEntries(keys.map(k=>{const value=parseAmount(fields[k]);if(value!==null&&value<0)throw Error('Metas e saldos iniciais precisam ser positivos ou zero.');if(value===null&&['monthlyGoal','emergencyOpening','businessOpening'].includes(k))throw Error('Preencha a meta mensal e os saldos iniciais.');return[k,value];}));const settings={...initial,...amounts,startMonth:start,kinds} as Settings;const r=await api<{settings:Settings;settingsVersion:number}>('/api/settings','PUT',{settings,version:store.settingsVersion});onSave(r.settings,r.settingsVersion);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const labels={monthlyGoal:'Meta mensal para guardar',emergencyGoal:'Meta total da emergência',businessGoal:'Meta total do caixa da empresa',emergencyOpening:'Saldo inicial da emergência',businessOpening:'Saldo inicial do caixa da empresa'};
 return <><section className="panel"><div className="panel-heading"><h2>Metas e ponto de partida</h2><Target size={20}/></div><div className="settings-grid">{keys.map(k=><label key={k}>{labels[k]}<div className="amount-field"><span>R$</span><input inputMode="decimal" placeholder={k.includes('Goal')?'Definir valor':'0,00'} value={fields[k]} onChange={e=>setFields({...fields,[k]:e.target.value})}/></div></label>)}<label>Início do acompanhamento<input type="month" min="2000-01" max="2099-12" value={start} disabled={store.months.length>0} onChange={e=>setStart(e.target.value)}/></label></div></section>
 <section className="panel settings-categories"><div className="panel-heading"><h2>Tratamento das categorias</h2><span className="badge">{CATEGORIES.length} categorias</span></div><div className="settings-category-grid">{CATEGORIES.map(c=><label key={c.id}><span>{c.name}</span><select value={kinds[c.id]} onChange={e=>setKinds({...kinds,[c.id]:e.target.value as Kind})}>{Object.entries(KIND_NAMES).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>)}</div>{error&&<div className="editor-error error-banner" role="alert">{error}<button onClick={onReload}>Recarregar dados</button></div>}<div className="save-bar"><span className={'save-state '+(dirty?'unsaved':'')}><span/>{dirty?'Alterações não salvas':'Tudo salvo'}</span><button className="button primary" onClick={save} disabled={busy}>{busy?<LoaderCircle size={18} className="spin"/>:<Save size={18}/>} Salvar configurações</button></div></section><section className="panel backup-panel"><div><h2>Seus dados com você</h2><p>Exporte os meses, as metas e as configurações.</p></div><a className="button secondary" href="/api/backup" download><Download size={18}/> Baixar backup</a></section></>;
}
function Guide(){const items=[
 ['Onde coloco o que gastei?','Em Gastos do mês. Escolha o mês e digite o total de cada categoria, como aparece no Nubank. Não é necessário detalhar cada compra. Clique em Salvar gastos para gravar no servidor.'],
 ['E as metas por categoria?','Em Planejamento. Informe a renda prevista, o limite de cada despesa e o aporte planejado. Você pode copiar as metas de um mês anterior já salvo. Metas não são gastos realizados.'],
 ['Vazio ou zero?','Deixe vazio o que ainda não foi informado. Digite zero quando não houve movimento. O botão Sem movimento = zero preenche somente os campos vazios. Você pode salvar parcialmente; para fechar o mês, todas as categorias não neutras precisam de um valor.'],
 ['Como corrijo um mês fechado?','Abra o mês em Gastos do mês, faça a correção e salve novamente. Salvar gastos deixa o mês Em andamento. Salvar e fechar mês confere se os campos obrigatórios estão completos e fecha novamente.'],
 ['Pagamentos e transferências','Começam como Neutro e ficam fora dos totais. Não conte o pagamento de fatura junto das compras já categorizadas. Transferências entre contas próprias não são renda nem consumo. Se uma categoria misturar gastos reais com transferências, recategorize antes de copiar os totais.'],
 ['Investimentos e Caixinhas','Informe os aportes menos os resgates, sem rendimentos. O resultado pode ser negativo. Não conte os resgates novamente em Recebimentos. Se parte desse valor não for para as duas reservas, informe o valor líquido em Outros investimentos fora das reservas.'],
 ['O que significa o saldo?','Saldo após aportes é receita menos despesas e todos os aportes líquidos. Não é o saldo da conta: não inclui o saldo bancário inicial nem movimentos neutros. A meta mensal de guardar considera o aporte para as reservas, descontando outros investimentos.'],
 ['Onde estou passando da meta?','O Dashboard compara o gasto e o limite de cada categoria de despesa. O ranking exibe os maiores excessos do mês. Categorias sem limite ficam fora do ranking. Defina limite zero quando decidir não gastar naquela categoria. Meses parciais continuam identificados.'],
 ['Reserva de emergência e caixa da empresa','Em Configurações, defina as metas e os saldos iniciais. O acumulado soma os saldos iniciais e os aportes líquidos das reservas desde o início até o mês selecionado. A destinação sugerida completa a emergência primeiro e coloca o restante na empresa. Não representa o saldo confirmado de cada caixinha.'],
 ['Resgates e projeções','Em resgates, o rateio sugerido reduz primeiro a parcela da empresa. A projeção de meses usa o que ainda falta e a meta mensal, sem rendimentos e sem novos resgates. Nenhum dinheiro é transferido pelo app.'],
 ['Anos, armazenamento e segurança','O seletor de mês permite acompanhar 2027 inteiro e os anos seguintes. Os valores ficam no banco da sua VPS e só são gravados ao salvar. Mantenha cópias de segurança fora da VPS. O backup em Configurações exporta os dados financeiros; o manual de instalação explica como restaurar.'],
 ['Conexão com o Nubank','Não há integração automática com o banco. Você copia os totais mensais. Use sempre o mesmo critério de mês e registre cada gasto uma única vez. O app não solicita credenciais bancárias.']
 ];return <section className="panel guide-panel"><div className="panel-heading"><div><h2>Uma rotina simples, todo mês</h2><span className="muted">As explicações ficam reunidas aqui.</span></div><BookOpen size={23}/></div><div className="guide-steps"><span><b>01</b> Planeje as metas</span><ArrowRight size={18}/><span><b>02</b> Registre os totais</span><ArrowRight size={18}/><span><b>03</b> Acompanhe as reservas</span></div>{items.map(([title,text],i)=><details key={title} open={i===0}><summary>{title}<Plus size={18}/></summary><p>{text}</p></details>)}</section>;}
